#!/bin/sh

# This script ensures the WiFi interface continues to provide DHCP services when necessary.

if [ "$ACTION" = "ifup" ] && [ "$INTERFACE" = "wlan0" ]; then
    if ! ip route | grep -q default; then
        # No default route, assume WiFi should act as LAN
        uci set network.wifi.ifname='wlan0'
        uci set dhcp.wifi.ignore='0'
    else
        # Default route exists, assume WiFi should not provide DHCP
        uci set dhcp.wifi.ignore='1'
    fi
    uci commit network
    uci commit dhcp
    /etc/init.d/network restart
    /etc/init.d/dnsmasq restart
fi

