sd_card: "/dev/sdb"
image_url: "https://downloads.raspberrypi.com/raspios_armhf/images/raspios_armhf-2024-03-15/2024-03-15-raspios-bookworm-armhf.img.xz"
image_path: "./2024-03-15-raspios-bookworm-armhf.img"
ssid: ""
wifi_password: ""
expected_checksum: "fae9616521dca981d2cc78e5527f9c6b16e5ae9ac7c8e5e38ff9f710231c5a23"
pi_username: ""
pi_password: ""
